### ISSUE TITLE
Broken tests

### ISSUE THREAD

**Issue by marcel-goldschen-ohm** [JuliaStats/Clustering.jl#135]
Julia 1.0.3, MacOSX 10.14.1: Running `test Clustering` gives one Broken test each for silhouettes(), MCL and V-measure.

**Comment by nalimilan** [comment]
Please check your install, clearly there's something broken (x-ref https://github.com/JuliaStats/StatsBase.jl/issues/441 and https://github.com/JuliaData/DataFrames.jl/issues/1669).

**Comment by marcel-goldschen-ohm** [comment]
Sorry to flood you with the broken tests, I now see that you are maintaining all those packages. I tried:
pkg> remove Clustering
pkg> add Clustering
pkg> test Clustering
with the same results (Clustering v0.12.1). How else might I go about checking my install? If this is an obvious question, I apologize, I'm new to Julia.

**Comment by marcel-goldschen-ohm** [comment]
Update: I previously had installed Julia via Homebrew. I tried installing it on a new machine (nearly brand new Mac) by downloading the mac app bundle instead. With the bundle version of Julia 1.0.3, I no longer get the DataFrame constructor errors (JuliaData/DataFrames.jl#1669), so maybe there is an issue with the homebrew version or something else got updated that needed to be? However, I still get the errors above for Clustering and for StatsBase (JuliaStats/StatsBase.jl#441). This is a brand new machine with fresh install. Also tried for example `pkg> update Clustering`, but did not help.

**Comment by marcel-goldschen-ohm** [comment]
Gotcha. Will do.

Cheers,
Marcel

---------------------------------------
Marcel Goldschen-Ohm | Assistant Professor, Department of Neuroscience<http://neuroscience.utexas.edu>
The University of Texas at Austin<http://www.utexas.edu> | 100 E 24th St, NHB 2.504, Austin TX 78712 | 512-232-1677

On Jan 10, 2019, at 3:56 AM, Milan Bouchet-Valat <notifications@github.com<mailto:notifications@github.com>> wrote:


Please create a new post on Discourse, there seems to be a deeper problem which isn't a bug on any of these packages, but in a deeper component.
