### ISSUE TITLE
Warnings with v12.2:  pairwise(…) should be replaced by pairwise(…, dims=2)

### ISSUE THREAD

**Issue by Djoop** [JuliaStats/Clustering.jl#146]
Just for reference (it's only a warning yet, but I guess it will become an error at some point):
```
┌ Warning: implicit `dims=2` argument now has to be passed explicitly to specify that distances between columns should be computed
│   caller = _kmeans!(::Array{Float64,2}, ::Nothing, ::Array{Float64,2}, ::Array{Int64,1}, ::Array{Float64,1}, ::Array{Int64,1}, ::Array{Float64,1}, ::Int64, ::Float64, ::Int64, ::Distances.SqEuclidean) at kmeans.jl:115
└ @ Clustering ~/.julia/packages/Clustering/pvAp6/src/kmeans.jl:115

```

Using Clustering.jl v12.2, Distances 0.8.0,  julia 1.1.0.

It looks like it comes from the calls to `pairwise` and `pairwise!` from the Distances.jl package. I think I got only the first warning, because it looks like there are a few different places where these functions are called.

**Comment by nalimilan** [comment]
Would you make a pull request to add `dims=2` to all calls?
