### ISSUE TITLE
Init with vector of int not supported

### ISSUE THREAD

**Issue by robertu94** [JuliaStats/Clustering.jl#162]
The current version of Clustering.jl does not support a vector of seed points for Kmeans per the [docs](http://juliastats.github.io/Clustering.jl/latest/kmeans.html#Clustering.kmeans):

```julia
using Clustering
points = rand(2,8)
init_points = [1,3,7]
println(Clustering.kmeans(points', 3, init=init_points))
```

```
LoadError: TypeError: in keyword argument init, expected Symbol, got Array{Int64,1}
Stacktrace:
 [1] (::getfield(Clustering, Symbol("#kw##kmeans")))(::NamedTuple{(:init,),Tuple{Array{Int64,1}}}, ::typeof(kmeans), ::Array{Float64,2}, ::Int64) at ./none:0
 [2] top-level scope at none:0
```

Tested using `[aaaa29a8] Clustering v0.13.0`

**Comment by Thuener** [comment]
I also had this issue. The change was on v0.12.3 that does `init::Symbol=_kmeans_default_init` this limit the seed usage.

https://github.com/JuliaStats/Clustering.jl/commit/c0f816f8c04d00039501253559df844a68c6a96c
