### ISSUE TITLE
hclust breaks on equal distances

### ISSUE THREAD

**Issue by altre** [JuliaStats/Clustering.jl#176]
`hclust(fill(3.141592653589, 4,4), linkage=:average)`
returns:
`ERROR: BoundsError: attempt to access 0-element Array{Array{Int64,1},1} at index [3]`

In this case the error appears due to numerical imprecision which leads to the order created in orderbranches_r! accessing cluster indices before their creation.
```Clustering.hclust_nn_lw(fill(3.141592653589, 4,4), Clustering.AverageDistance(fill(3.141592653589, 4,4))).heights
3-element Array{Float64,1}:
 3.141592653589    
 3.141592653589    
 3.1415926535889995
```

However there also seem to be cases where there is no obvious precision problem. In the matrix here:
[problem.txt](https://github.com/JuliaStats/Clustering.jl/files/3631243/problem.txt)
the same error occurs.

**Comment by alyst** [comment]
Thanks for the great examples!

**Comment by altre** [comment]
I'm not 100% sure this is the same problem, but 
[problem2.txt](https://github.com/JuliaStats/Clustering.jl/files/3635573/problem2.txt) leads to: 
```
julia> hclust(dists, :average)
ERROR: AssertionError: 1 ≤ i=1 < j=14 <= N=11 ≤ 130
``` 
I'm assuming it's related because there are many equal values and adding small random jitter to the matrix removes the error:
```
julia> tu = dists .+ randn(size(dists)) ./ 100000;
julia> dists_jitter = triu(tu) + triu(tu)';
julia> hclust(dists_jitter, :average)
Hclust{Float64}([-6 -130; -8 -22; … ; -123 127; 120 128], [0.006944855745030266, 0.006947569706766777, 0.00694837590908215, 0.00694909933583263, 0.006950774440969502, 0.0069517185995807956, 0.006955170583773857, 0.006955266164221605, 0.006956266302993133, 0.006956422780102605  …  0.8382236746140419, 0.8446644153601236, 0.8471301824959012, 0.8474461931610402, 0.8501122354788007, 0.8503626829354424, 0.8554644798496454, 0.8636972184351754, 0.8951906644218878, 0.9109219167654417], [82, 109, 85, 93, 112, 62, 98, 117, 74, 73  …  122, 110, 69, 59, 38, 61, 35, 127, 67, 111], :average)
```  
This workaround is sufficient for me at the moment, but I thought I would point out the problem.

**Comment by alyst** [comment]
That's even better example! I've fixed it in the PR, although I'm not sure whether the fix is optimal. Let me know if it works for you.
