### ISSUE TITLE
kmeans() and kmedoids() don't support k=1 and k=n

### ISSUE THREAD

**Issue by theogf** [JuliaStats/Clustering.jl#183]
Right now if the number of centers `k` is equal to the number of points, `kmeans` returns an error, shouldn't the behavior be to return the whole data?

**Comment by birm** [comment]
Likewise, having one point would just return a random (or given) vector. Are these cases useful to add?

**Comment by alyst** [comment]
I agree, both `kmeans()` and `kmedoids()` should support `k=1` (all points in one cluster) and `k=n` (each point in its own cluster) corner cases.
The PR fixing this is welcome!

**Comment by alyst** [comment]
I agree, both `kmeans()` and `kmedoids()` should support `k=1` (all points in one cluster) and `k=n` (each point in its own cluster) corner cases.
The PR that fixes this would be welcome!
