### ISSUE TITLE
DBSCAN not returning every point in the list

### ISSUE THREAD

**Issue by bodhi91** [JuliaStats/Clustering.jl#190]
Hi,

This may not be a critical issue but I find that dbscan often fails to return every point in the list. I believe these points which fail to show up are outliers, but even if that is the case shouldn't we be assigning them as independent clusters and return the complete assignment list? 

`v = [.828 .134 .821 .630 .784 .674 .674 .436 .089 .777 .526 .200 .908 .929 .835 .553 .647 .672 .234 .536 .617; 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0];
r = dbscan(v, 0.075, min_cluster_size=3)`

`3-element Array{DbscanCluster,1}:
 DbscanCluster(7, [1, 3, 5, 9, 12, 13, 14], Int64[])
 DbscanCluster(4, [2, 8, 11, 18], Int64[])
 DbscanCluster(8, [4, 6, 10, 15, 16, 17, 19, 20], Int64[])`

This return 3 clusters but fails to assign point 7 which I believe is an outlier. I was wondering shouldn't we be returning all cluster assignments including outliers? Or maybe I am missing something here?

**Comment by tvannoy** [comment]
Just to add to this, my primary interest right now in using DBSCAN is to *detect*, not remove, outliers. The reported behavior in this issue, as well as the api documentation, suggests that outliers are discarded, which makes the DBSCAN implementation here a no-go for me.

**Comment by alyst** [comment]
Sorry, this comes late, but for the posterity.
With #248 the API would change:
```julia
r = dbscan(v, 0.075, result_type=DbscanResult min_cluster_size=3)
```
would return `DbscanResult` both for point coordinates and distance matrices.
`r.assignments` will store the assigned cluster index for all points, and *0* if the point was not assigned to any cluster (outlier).
