### ISSUE TITLE
Use latest NearestNeighbors

### ISSUE THREAD

**Issue by tlienart** [JuliaStats/Clustering.jl#194]
Is there a reason why this package requires a very old version of NearestNeighbors.jl (0.0.3 as opposed to latest existing version 0.4.4)?

**Comment by alyst** [comment]
There's no upper bound for requirements, so it's using the latest versions of the packages, including *NearestNeighbors.jl*.
Which may be suboptimal, I'm considering introducing upper bounds as the other packages do.

**Comment by tlienart** [comment]
Ah right, sorry I looked at the REQUIRE file assuming it behaved liked the Project.toml which obviously it doesn't.
