### ISSUE TITLE
Docu for DBscan

### ISSUE THREAD

**Issue by MRIO** [JuliaStats/Clustering.jl#201]
https://clusteringjl.readthedocs.io/en/latest/dbscan.html

...has a problem displaying the resulting structure of the dbscan on the adjacency list method.

<img width="735" alt="image" src="https://user-images.githubusercontent.com/8012564/88283555-46322780-ccf4-11ea-9f68-73a4da79c731.png">

**Comment by alyst** [comment]
This problem is fixed in the new docs.
