### ISSUE TITLE
Readthedocs github link broken

### ISSUE THREAD

**Issue by MRIO** [JuliaStats/Clustering.jl#202]
Howdy all,

I wanted to repair a small problem in the docu, but when i tried to click on the readthedocs github link, i landed on a 404.

This is where http://clusteringjl.readthedocs.io/ pointed me to:
https://github.com/JuliaStats/Clustering.jl/blob/master/doc/source/dbscan.rst

And nothing there...

**Comment by nalimilan** [comment]
The ReadTheDocs page is outdated, now docs live under http://juliastats.github.io/Clustering.jl/stable/ (as linked in README.md).

It would be nice to remove the ReadTheDocs project, but AFAICT only @lindahua can do that. Dahua, could you do that? https://readthedocs.org/projects/clusteringjl/
