### ISSUE TITLE
Add way to set random seed to a number

### ISSUE THREAD

**Issue by f0lie** [JuliaStats/Clustering.jl#214]
There isn't a clear cut way to set the random seed of the kmeans or any algorithm to get the same results.

**Comment by alyst** [comment]
The algorithms use the default Julia random generator. You can set the random seed from your script before running the clustering.

**Comment by f0lie** [comment]
This could be a little snip it to put into the documentation. I did successfully set the random seed with
```julia
using Random
Random.seed!(1234)
```
