### ISSUE TITLE
conflict of "pairwise" in procedure `kmeans.jl`

### ISSUE THREAD

**Issue by tangwang-USTC** [JuliaStats/Clustering.jl#235]
Both module Distance.jl and StatsBase.jl export "pairwise", uses of it in module Clustering must be qualified.

**Comment by wildart** [comment]
`pairwise` defined in StatsAPI.jl and both Distance.jl and StatsBase.jl override it. There should be problem with it.

**Comment by alyst** [comment]
@tangwang-USTC As @wildart has noted, recent versions of *Distances.jl* and *StatsBase.jl* both import *pairwise()* from *StatsAPI.jl*. Have you tried to update your environment [(`]up`)](https://docs.julialang.org/en/v1/stdlib/Pkg/)? If the problem persist, could you please provide an example of the command that you try to run and the output that you get?
