### ISSUE TITLE
Docs not deployed for tags. 

### ISSUE THREAD

**Issue by alyst** [JuliaStats/Clustering.jl#247]
Since the CI switched from Travis.yml to GH actions, the stable docs are not deployed when the new tag is created (gh-pages branch misses the corresponding folder). Dev docs are still correctly deployed.

**Comment by alyst** [comment]
@ararslan You should know the CI mechanics much better than I do. Could you please take a look?

**Comment by ararslan** [comment]
I submitted #249 in an attempt to fix this but I'm not certain it will actually fix it. Worth a try though!

**Comment by alyst** [comment]
It was a problem of TagBot.yml provided only with GITHUB_TOKEN not having permissions to initiate other github actions.
Solved by adding DOCUMENTER_KEY in commit d4cb6af21b4e7cfb1d089389daa5a5eecd53ad2b.
