### ISSUE TITLE
Providing additional intrinsic evaluation metrices

### ISSUE THREAD

**Issue by jaksle** [JuliaStats/Clustering.jl#253]
This is more of a question than an issue. I wanted to time series clustering using Clustering.jl and I needed intrinsic evaluation measures in order to determine optimal number of clusters. Clustering.jl offers only silhouettes in this regard so I implemented myself popular ones: Calinski-Harabasz, Davies-Boulden, Xie-Beni indices. Would it be useful if I add them to Clustering.jl?

The formulas are easy so it would not require a lot of work, it's just that first I would like to be sure there is an interest in that.

**Comment by nomadbl** [comment]
Not a maintainer here or anything, but sounds interesting to me :smile:

**Comment by alyst** [comment]
Sure, this sounds very useful! One constraint, though, is that we don't want *Clustering.jl* to be a super-package for anything related to unsupervised learning as that would complicate maintenance and unnecessary bloat user projects.
So new features that would require extra dependencies, esp. outside of *github.com/JuliaXXX* ecosystem, or features that add a lot of new relatively complex code, should rather be implemented as separate packages.

If these new metrics fit the above criteria, the PR is welcome! :)

**Comment by jaksle** [comment]
No new dependencies needed, no complex code, these quality indices have definitions simpler than silhouettes.  Bloat is not my goal, but the few most popular indices for hard and soft clustering I hope would come in handy.

So great, now I am busy but next month I will try check and adjust my code :)

**Comment by alyst** [comment]
Implemented in #257
