### ISSUE TITLE
Is this package actively maintained? By who?

### ISSUE THREAD

**Issue by juliohm** [JuliaStats/Clustering.jl#275]
Please comment here if you are a maintainer of Clustering.jl

**Comment by alyst** [comment]
@juliohm I try to maintain it when I find time (as you can judge from the commit history). What's the "issue"? :)

**Comment by juliohm** [comment]
Wanted to double check that someone is actively making hard decisions here.
Feel free to close the issue.

Em sáb., 30 de mar. de 2024, 16:38, Alexey Stukalov <
***@***.***> escreveu:
