### ISSUE TITLE
Add docs website to the "About" section on github

### ISSUE THREAD

**Issue by vituri** [JuliaStats/Clustering.jl#282]
The "About" section is the most usual place to put the docs website. I had to find the link on the "Deployments" section.

http://juliastats.org/Clustering.jl/

**Comment by alyst** [comment]
We have documentation badges in the README.md -- which is the conventional location of the documentation links for Julia projects.
Do you mean something else by the "About" section?

**Comment by vituri** [comment]
Ops, sorry if I was not clear. I mean this section:

![image](https://github.com/user-attachments/assets/7c29d226-7b4e-41af-92b4-f7587a0ca595)

Usually almost all packages I see have the docs on this part of the github page.

**Comment by alyst** [comment]
Ah, now I see! Thanks, I have added the link.
