### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaStats/Clustering.jl#38]
doc/source/varinfo.rst is not showing up on the readthedocs site for the latest build.
Are there any other functions that are missing from the documentation?
When I built it locally varinfo was there.

**Comment by johnmyleswhite** [comment]
I don't understand enough about readthedocs is configured to say. If I have time to look into it, I'll try to see what's going on, but no promises.

**Comment by jpfairbanks** [comment]
This is magically fixed unless someone wants to claim credit.
