### ISSUE TITLE
Hierarchical clustering?

### ISSUE THREAD

**Issue by dreiss-isb** [JuliaStats/Clustering.jl#4]
Any plans / interest to add hierarchical clustering to this package? Or is that more appropriate for a different package? In that case, this package should be renamed to Kmeans or some such.

**Comment by diegozea** [comment]
There is already a function for hierarchical clustering, but the API doesn't follow the style of this package. Is It possible to...

- ...make `Hclust` a sub-type of `ClusteringResult`?  
- ...rename `cutree` to `assignments` (with `h` and `k` keyword arguments)?
- ...define `counts` with  `h` and `k` keyword arguments?
- ...define `nclusters` with `h` keyword argument?

Also, the name `hierarchical` sounds more Julian than `hclust`.

If it's ok, I could make a PR after https://github.com/JuliaStats/Clustering.jl/pull/59 (and maybe https://github.com/JuliaStats/Clustering.jl/pull/60) get merged. 

What do you think?

Thanks! 

Best

**Comment by diegozea** [comment]
Bump!

**Comment by kmsquire** [comment]
I think that would be fine.  Do you feel comfortable reviewing #59 and #60?  I think they could probably be merged if someone reviewed them and gave some feedback (even a "looks good").

**Comment by diegozea** [comment]
After viewing the changes and comparing results with R, https://github.com/JuliaStats/Clustering.jl/pull/59 looks good ;)

**Comment by ararslan** [comment]
Now that we have `HClust` in here, I'll close this as having been addressed.

**Comment by diegozea** [comment]
@ararslan Was there a recent merged PR addressing the documentation and API of `HClust` to close this?

**Comment by ararslan** [comment]
@diegozea Heirarchical clustering was introduced in #32. There's still an outstanding PR (#60) to add documentation, but since this issue is asking for heirarchical clustering functionality and that's now available, it seems to me that the issue has been effectively addressed.

**Comment by diegozea** [comment]
@ararslan What do you think about this proporsal: https://github.com/JuliaStats/Clustering.jl/issues/4#issuecomment-193540219  
I'm sorry. I haven't had time to work on it yet...

**Comment by ararslan** [comment]
What you propose in that comment sounds great to me!
