### ISSUE TITLE
New validation measures

### ISSUE THREAD

**Issue by jumutc** [JuliaStats/Clustering.jl#48]
Hello folks,

What about new validation measures for clustering like: Rand index, Adjusted Rand index etc.?
Please take a look at this [Wikipage](https://en.wikipedia.org/wiki/Rand_index) and corresponding publication in [Journal of Classification](http://link.springer.com/article/10.1007/BF01908075).

**Comment by johnmyleswhite** [comment]
Pretty busy these days, but I'll try to review your PR in a few weeks.
