### ISSUE TITLE
tag a new release of Clustering.jl ?

### ISSUE THREAD

**Issue by jeff-regier** [JuliaStats/Clustering.jl#56]
I submitted a PR last week that suppressed warnings from Julia 0.4, but these changes never got released. Without the changes, Clustering.jl generates so many warnings that it's hard to use. (Running the unit tests for Clustering.jl generates over 16,000 lines of warning messages currently.)  Will you a tag a new release? Thanks much!

**Comment by rasmusbrandt** [comment]
+1

**Comment by johnmyleswhite** [comment]
Done
