### ISSUE TITLE
DBSCAN should not require a distance matrix

### ISSUE THREAD

**Issue by kno10** [JuliaStats/Clustering.jl#58]
Distance matrixes are too expensive.
They need O(n^2) memory, and thus O(n^2) time to create.

Better DBSCAN implementations use indexes for acceleration.

**Comment by johnmyleswhite** [comment]
Thanks for the tip. Closing as a non-priority.

**Comment by kmsquire** [comment]
@kno10, a pull request which implemented the indexed based method would be welcome!

**Comment by kno10** [comment]
Even without an index, it would allow running the algorithm on much larger data.
By precomputing a distance matrix, you run of out memory at 50k instances, which is not too big yet.
It takes about 90 seconds on a single core in C++ to run DBSCAN on 110k instances, but Julia is out of memory at half of that data size (also affects e.g. hclust).

Don't expect a pull request from me: I've written less than 10 lines of Julia, and it already annoyed me that it uses column-major when every language I use else uses row-major order ...

**Comment by simonster** [comment]
I don't really know the algorithm here and I'm not making a commitment to implement anything, but perhaps this as simple as using `inball` from NearestNeighbors.jl in place of [`_dbs_region_query`](https://github.com/JuliaStats/Clustering.jl/blob/3f1fd76d943cc8a4ab600f692cc6622d1b8fba76/src/dbscan.jl#L62-L72)?

**Comment by kno10** [comment]
@simonster yes, that function is meant to retrieve all objects within a radius epsilon (including the query point)

**Comment by KristofferC** [comment]
You could also look at (the package which happens to have the same name...) https://github.com/KristofferC/NearestNeighbors.jl which is quite fast.

```
KDTree(rand(3,10^6))
  1.601745 seconds (100.02 k allocations: 65.614 MB, 2.79% gc time)

@time nbs = inrange(tree, rand(3,10^6), 0.01)
  4.153109 seconds (2.41 M allocations: 170.713 MB, 14.72% gc time)
```

**Comment by KristofferC** [comment]
Reopening this since it seems like it is more likely to get work done on if it is seen by more people. Doesn't mean anyone is actively working on it.

**Comment by OmriRoames** [comment]
Is anyone still interested in it? I have an implementation that uses an adjacency list so it's memory efficient. It also keeps track of the core and boundary.

**Comment by ararslan** [comment]
@OmriRoames I don't see why not. Pull requests are always welcome. 😄

**Comment by OmriRoames** [comment]
Well... I've made one 4 months ago and didn't get any response #61. The test failed for julia 0.3 because NearestNeighbors needs 0.3.12 or higher. This is the error: "ERROR: NearestNeighbors can't be installed because it has no versions that support 0.3.12 of julia. You may need to update METADATA by running `Pkg.update()` "

I've made a few changes since the pull request so if you want to loot at it I'll update it.

**Comment by KristofferC** [comment]
Tagging a new version that drops support for 0.3 should be fairly uncontroversial from my p.o.v.

**Comment by OmriRoames** [comment]
Is it possible to have NearestNeighbors support julia 0.3?

**Comment by KristofferC** [comment]
Possibly, I don't think I use any real new features in 0.4 for it so it should theoretically be just to add `@compat` macros where needed. I would merge a PR that does this but I will not work on it myself.

**Comment by ararslan** [comment]
This package current requires Julia 0.4 but there hasn't been a tag for that yet. I'd be happy to do that.

**Comment by OmriRoames** [comment]
OK, it's updated and rebased in a new PR #69

**Comment by garborg** [comment]
Closed by #69?

**Comment by andyferris** [comment]
+1 for closing once the docs are rebuilt so the algorithm is visible to the public.

**Comment by OmriRoames** [comment]
+1 for closeing
