### ISSUE TITLE
What's up with Clustering's tags?

### ISSUE THREAD

**Issue by sbromberger** [JuliaStats/Clustering.jl#62]
I notice that at https://github.com/JuliaStats/Clustering.jl/tags, v0.3.3 is the highest version. But over at LightGraphs, we're requiring 0.4, and your README shows 0.5. Where are these located? Is it the case that git tags do not correlate with Julia versions? (They appear to in LightGraphs.)

**Comment by KristofferC** [comment]
Why would a package tag has anything to do with the julia version?

**Comment by sbromberger** [comment]
@KristofferC mainly because the advertised release process is

```
Pkg.tag("Mypackage")
Pkg.publish()
```
?

**Comment by KristofferC** [comment]
`Pkg.tag` just increments the minor version of a package? Isn't someone just doing it manually for LightGraphs?

```jl
julia> using PkgDev

julia> PkgDev.generate("TestPKG", "MIT")

julia> PkgDev.tag("TestPKG")
INFO: Tagging TestPKG v0.0.1

julia> PkgDev.tag("TestPKG")
INFO: Tagging TestPKG v0.0.2

julia> PkgDev.tag("TestPKG")
INFO: Tagging TestPKG v0.0.3

julia> PkgDev.tag("TestPKG")
INFO: Tagging TestPKG v0.0.4

julia> PkgDev.tag("TestPKG")
INFO: Tagging TestPKG v0.0.5

julia> PkgDev.tag("TestPKG")
INFO: Tagging TestPKG v0.0.6

julia> PkgDev.tag("TestPKG")
INFO: Tagging TestPKG v0.0.7

julia> PkgDev.tag("TestPKG")
INFO: Tagging TestPKG v0.0.8
```

**Comment by sbromberger** [comment]
We've generally used the autoincrement, but `Pkg.tag()` can take a second argument that's an explicit version number.

In any case, I think the core of the issue is that for some reason, Clustering can't precompile, and that's causing an initial cascading failure in LightGraphs.

**Comment by KristofferC** [comment]
> `__precompile__()` should not be used in a module unless all of its dependencies are also using `__precompile__()`.

**Comment by sbromberger** [comment]
At some point I thought we switched to default precompilation.

**Comment by KristofferC** [comment]
I don't think that ever happened.
