### ISSUE TITLE
WARNING: both ArrayViews and Base export "view"

### ISSUE THREAD

**Issue by cormullion** [JuliaStats/Clustering.jl#66]
Testing on 0.5.0-dev+5478 gives:

`WARNING: both ArrayViews and Base export "view"; uses of it in module Clustering must be qualified`

Although ArrayViews.jl now says:

> By and large, this package is no longer necessary: base julia now has efficient SubArrays (i.e., sub and slice).

Eventually giving errors like this:

```
ERROR: LoadError: UndefVarError: view not defined
 in initseeds!(::Array{Int64,1}, ::Clustering.KmppAlg, ::Array{Float64,2}, ::Distances.SqEuclidean) at /Users/me/.julia/v0.5/Clustering/src/seeding.jl:98
```

**Comment by ararslan** [comment]
Thanks for bringing this up, @cormullion. Looks like there's some updating to be done; we recently made similar changes to another package to fix this. I'll see if I can get to this early this week.
