### ISSUE TITLE
inconsistent use of `minpts` parameter in DBSCAN

### ISSUE THREAD

**Issue by twadleigh** [JuliaStats/Clustering.jl#67]
In the [body of `_dbscan`](https://github.com/JuliaStats/Clustering.jl/blob/c18336745cc7e0236d5a63a174dacb080db532c4/src/dbscan.jl#L47) the `minpts` parameter is used with non-strict inequality, whereas it is used with strict inequality in the [body of `_dbs_expand_cluster](https://github.com/JuliaStats/Clustering.jl/blob/c18336745cc7e0236d5a63a174dacb080db532c4/src/dbscan.jl#L89). They should be consistent, and the usual convention is that the test be non-strict.

I'd create the single-character pull request myself, but I currently don't have the set up to do that easily.

**Comment by andyferris** [comment]
Single character pull requests are easy using the Github web interface. You can modify a file and make a PR in just a few clicks. Of course, you can't test for unintended consequences (except for existing unit testing).
