### ISSUE TITLE
Please tag latest version in METADATA

### ISSUE THREAD

**Issue by davidavdav** [JuliaStats/Clustering.jl#71]
Hello, 

I am in the process of making GaussianMixtures compatible with julia v0.5.  GaussianMixtures depends on Clustering.  It needs the latest commits in order to compile.  I don't see a way how I can depend on a specific commit, so the request is to tag the latest commit with METADATA. 

Thanks a lot, 

---david

**Comment by ararslan** [comment]
Will do 👍

**Comment by ararslan** [comment]
Done. The newest version is Clustering 0.6.0, which should play nicely with Julia 0.5. Thanks for bringing this to our attention!

**Comment by davidavdav** [comment]
Great! Thanks.

**Comment by davidavdav** [comment]
Hello, 

I've really tried everything but I don't seem to be able to load this tagged version in v0.5.  It seems to stay stuck at Clustering v0.5.0. 

I've
- removed `~/.julia/v0.5`
- rebuilt today's version of julia-0.5
- removed all packages and added them back again with `Pkg.rm()` and `Pkg.add()`
- tried to checkout Clustering-0.6.0 with `Pkg.checkout()`

but nothing works, really.  I've looked at this package's git log, and it seems that there is a
- branch 0.6.0 (at 3f1fd76)
- branch v0.6.0 (at 3f1fd76)
- tag v0.6.0 (at 3c4c28e)

Maybe this is confusing the package management system.

**Comment by ararslan** [comment]
The branches you noted aren't active branches; they don't show up in the branch list. Could you provide the output of `Pkg.status()`? That might help shed some light on whether different stats packages are requiring different versions of a particular dependency thereby keeping this from upgrading.

**Comment by davidavdav** [comment]
OK, I think it was my bad. 

For some reason `Pkg.add("GaussianMixtures")` kept downgrading a whole lot of packages, a.o. Clustering to 0.5.0.  My guess is that the registered version of GaussianMixtures depended on ArrayViews, although I don't see that in the old REQUIRE.  Perhaps I had to specify the minimum version of Clustering in REQUIRE, anyway, [it seems to be fixed](https://travis-ci.org/davidavdav/GaussianMixtures.jl) now.

**Comment by ararslan** [comment]
Great, I'm glad you got things working!
