### ISSUE TITLE
Docs out of date

### ISSUE THREAD

**Issue by andyferris** [JuliaStats/Clustering.jl#74]
Hi,

The docs haven't seem to be built for 1 year and 5 months. Has someone done this:

http://read-the-docs.readthedocs.io/en/latest/webhooks.html

**Comment by ararslan** [comment]
Looks like the ReadTheDocs webhook wasn't set up here. I just set it up using the directions in your link. Thanks!

**Comment by andyferris** [comment]
Thanks. Faster issue fixed EVER. :)

**Comment by andyferris** [comment]
I suppose it won't update automatically until there is a push. Is there a manual build option for an immediate refresh?

**Comment by ararslan** [comment]
Not that I've seen. (It's entirely possible that there is one and it's super obvious and I'm just oblivious)
