### ISSUE TITLE
tag new release...

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaStats/Clustering.jl#83]
and add 0.6 badge to readme, now that #82 is merged?

**Comment by ararslan** [comment]
The `InexactError` on 0.6 macOS is still troublesome to me. It may be best to figure that out before we claim to fully support 0.6, though I'm not adamant about that.

@simonbyrne You're a numerical accuracy guru; any idea what's going on with the Mac failure?

**Comment by ararslan** [comment]
New release tagged. Should be merged into METADATA soon.
