### ISSUE TITLE
DBSCAN gives error on Float32 array

### ISSUE THREAD

**Issue by azsigmon** [JuliaStats/Clustering.jl#84]
I can only use the DBSCAN algorithm with a Float64 array but not with a Float32 array, that is actually my input.

`
using Clustering; positions = zeros(Float32, 3, 10); clusters = dbscan(positions, 0.3, min_neighbors=1, min_cluster_size=1, leafsize=20)
`

ERROR: MethodError: no method matching _dbscan(::NearestNeighbors.KDTree{StaticArrays.SVector{3,Float32},Distances.Euclidean,Float32}, ::Array{Float32,2}, ::Float64; min_neighbors=1, min_cluster_size=1)
Closest candidates are:
  _dbscan{T<:AbstractFloat}(::NearestNeighbors.KDTree{V<:AbstractArray{T,1},M<:Union{Distances.Chebyshev,Distances.Cityblock,Distances.Euclidean,Distances.Minkowski},T}, ::Array{T<:AbstractFloat,2}, ::T<:AbstractFloat; min_neighbors, min_cluster_size) at /user/.julia/v0.5/Clustering/src/dbscan.jl:144
 in #dbscan#6(::Int64, ::Array{Any,1}, ::Function, ::Array{Float32,2}, ::Float64) at /user/.julia/v0.5/Clustering/src/dbscan.jl:137
 in (::Clustering.#kw##dbscan)(::Array{Any,1}, ::Clustering.#dbscan, ::Array{Float32,2}, ::Float64) at ./<missing>:0

**Comment by wildart** [comment]
Type of the data and the radius should be the same.

```julia
positions = zeros(Float32, 3, 10)
clusters = dbscan(positions, 0.3f0, min_neighbors=1, min_cluster_size=1, leafsize=20)
```
The #101 should provide better error message when types are mixed.
