### ISSUE TITLE
test failure on OS X with 0.6

### ISSUE THREAD

**Issue by simonbyrne** [JuliaStats/Clustering.jl#87]
The cause is `mcl`: here is a simple reproducible example:
```
adj_matrix = [1.0 0.125 1.0 0.0 0.16 0.0; 0.125 1.0 0.0 0.25 0.0 0.16; 1.0 0.0 1.0 0.0 0.2 0.0; 0.0 0.25 0.0 1.0 0.0 0.5; 0.16 0.0 0.2 0.0 1.0 0.0; 0.0 0.16 0.0 0.5 0.0 1.0]
mcl(adj_matrix, display=:verbose, inflation=1.5, expansion=1.5, save_final_matrix=true)
```

I had a quick look through, my guess is that there is a slight change in BLAS behaviour which causes `eig` to give subtly different values, and that this error then amplifies, but i don't understand the algorithm well enough to be sure.

**Comment by ararslan** [comment]
cc @alyst
