### ISSUE TITLE
`kmeans` dispatch problem

### ISSUE THREAD

**Issue by annimesh2809** [JuliaStats/Clustering.jl#91]
The current implementation of `kmeans` has the following declaration:
```julia
function kmeans(X::Matrix, k::Int;
                weights=nothing,
                init=_kmeans_default_init,
                maxiter::Integer=_kmeans_default_maxiter,
                tol::Real=_kmeans_default_tol,
                display::Symbol=_kmeans_default_display)
```
although it calls the function `kmeans!` whose declaration is:
```julia
function kmeans!{T<:AbstractFloat}(X::Matrix{T}, centers::Matrix{T};
                                   weights=nothing,
                                   maxiter::Integer=_kmeans_default_maxiter,
                                   tol::Real=_kmeans_default_tol,
                                   display::Symbol=_kmeans_default_display)

```
Here `T` is a subtype of `AbstractFloat`. This constraint in `T` is not present in `kmeans` which allows us to call `kmeans` as:
```julia
kmeans(rand(Int,3,100), 5)
```
which throws an error.

I also require `kmeans{T}` to be constrained with `T<:AbstractFloat` because I am dispatching on `kmeans` for [ImageSegmentation](https://github.com/JuliaImages/ImageSegmentation.jl/pull/11) as:
```julia
kmeans{T<:Colorant,N}(x::AbstractArray{T,N}, args...; kwargs...)
```

**Comment by kmsquire** [comment]
closed by #92
