### ISSUE TITLE
Bounds Error with Hclust on large Matrix

### ISSUE THREAD

**Issue by kescobo** [JuliaStats/Clustering.jl#93]
I'm trying to do hierarchical clustering on large-ish distance matrices. The following works fine:

```julia
using Distances
using Clustering

m1 = rand(100,100)
d1 = pairwise(Jaccard(), m1)
c1s = hclust(d1, :single)
c1a = hclust(d1, :average)
```

I was able to do it on a random table as big as 10k x 10k, but for my actual datatable which is about 12k x 12k, the `:single` works, but `:average` hclust produces an error - (eventually, after a rather long time):

```
BoundsError: attempt to access 8947-element Array{Any,1} at index [8984]
hclust(::Symmetric{Float64,Array{Float64,2}}, ::Symbol) at hclust.jl:338
hclust(::Array{Float64,2}, ::Symbol) at hclust.jl:351
include_string(::String, ::String) at loading.jl:515
include_string(::String, ::String, ::Int64) at eval.jl:30
include_string(::Module, ::String, ::String, ::Int64, ::Vararg{Int64,N} where N) at eval.jl:34
(::Atom.##49#53{String,Int64,String})() at eval.jl:50
withpath(::Atom.##49#53{String,Int64,String}, ::String) at utils.jl:30
withpath(::Function, ::String) at eval.jl:38
macro expansion at eval.jl:49 [inlined]
(::Atom.##48#52{Dict{String,Any}})() at task.jl:80
```

Is this a memory error? I can do hclust in R for the same data, so iI think in principle it should work.

**Comment by nalimilan** [comment]
This doesn't sound like a memory error. Though maybe some memory corruption is happening, you could try starting Julia with `--check-bounds=yes` to be sure the error does not come from elsewhere.

The [relevant code](https://github.com/JuliaStats/Clustering.jl/blob/538efbbcf6fef61a81b9a95bcb97eae01dc11282/src/hclust.jl#L338) doesn't sound too complex. You could reproduce the problem by calling `hclust2` manually (like the function does at the top), and then run the rest of the lines at the REPL. The `merge` matrix is probably incorrect in some way, if you can save/post it somewhere it could be helpful for debugging.

**Comment by kescobo** [comment]
Sorry for leaving this issue hanging - I was in a rush and ended up just using Rcall. Alas, I didn't hang on to the underlying data. If this pops up again, will re-open.
